#!/usr/bin/python
#
# Produce example JSON to be POSTed to API backend
#
# $ ./example-json | curl --data-urlencode request@- -v localhost:8511/add_raw
#

import sys
import json

a = {'add_raw':
         {
        'data': {'verified': True,
                 'email': 'ft@example.net',
                 },
        },
     'version': 1,
     }

print json.dumps(a, sort_keys=True, indent=4)
