#!/usr/bin/python
#
# Produce example JSON to be POSTed to API backend
#
# $ ./example-json | curl --data-urlencode request@- -v localhost:8511/add_raw
#

import sys
import json
import time
import bcrypt

salt = bcrypt.gensalt()
credential_id = int(time.time() - 1370246844)

a = {'add_raw':
         {
        'data': {
            "sn": "Thulin",
            "givenName": "Fredrik",
            "eduPersonPrincipalName": "ft@eduid.se",
            "uid": "ft",
            "eduPersonTargetedID": "f.t.a.t.e.d.u.I.D",
            "c": "SE",
            "ou": "IT",
            "email": "fredrik@thulin.net",
            "displayName": "Fredrik Thulin",
            "norEduPersonNIN": "SE197001013333",
            # made-up attributes
            "eduID,private,salt": salt,
            "eduID,private,credential_id": credential_id,
            },
        },
     'version': 1,
     }

print json.dumps(a, sort_keys=True, indent=4)
